spring:
  application:
    name: consumer-service
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  provider:
    token: false
  registry:
    address: zookeeper://localhost:2181?backup=localhost:2182,localhost:2183
  protocol:
    name: dubbo
    port: -1