server:
  port: 8011
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
  application:
    name: shenyu-gateway
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  provider:
    token: false
  registry:
    address: zookeeper://localhost:2181?backup=localhost:2182,localhost:2183
  protocol:
    name: dubbo
    port: -1
shenyu:
  register:
    registerType: http #注册方式
    serverLists: http://localhost:9095 #注册地址
    props:
      username: admin
      password: 123456
  client:
    dubbo:
      props:
        contextPath: /dubbo
        appName: ${spring.application.name}