spring:
  application:
    name: provider-service
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  provider:
    token: false
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1